# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: threadname.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10threadname.proto\"\x13\n\x11ThreadNameRequest\"\"\n\x12ThreadNameResponse\x12\x0c\n\x04name\x18\x01 \x01(\t2G\n\x0bThreadNamer\x12\x38\n\rGetThreadName\x12\x12.ThreadNameRequest\x1a\x13.ThreadNameResponseb\x06proto3')



_THREADNAMEREQUEST = DESCRIPTOR.message_types_by_name['ThreadNameRequest']
_THREADNAMERESPONSE = DESCRIPTOR.message_types_by_name['ThreadNameResponse']
ThreadNameRequest = _reflection.GeneratedProtocolMessageType('ThreadNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _THREADNAMEREQUEST,
  '__module__' : 'threadname_pb2'
  # @@protoc_insertion_point(class_scope:ThreadNameRequest)
  })
_sym_db.RegisterMessage(ThreadNameRequest)

ThreadNameResponse = _reflection.GeneratedProtocolMessageType('ThreadNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _THREADNAMERESPONSE,
  '__module__' : 'threadname_pb2'
  # @@protoc_insertion_point(class_scope:ThreadNameResponse)
  })
_sym_db.RegisterMessage(ThreadNameResponse)

_THREADNAMER = DESCRIPTOR.services_by_name['ThreadNamer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _THREADNAMEREQUEST._serialized_start=20
  _THREADNAMEREQUEST._serialized_end=39
  _THREADNAMERESPONSE._serialized_start=41
  _THREADNAMERESPONSE._serialized_end=75
  _THREADNAMER._serialized_start=77
  _THREADNAMER._serialized_end=148
# @@protoc_insertion_point(module_scope)
